# RAG

In [14]:
# import json
# import torch
# from transformers import AutoTokenizer, AutoModel
# from sklearn.metrics.pairwise import cosine_similarity
# import requests
# import os
# import time

# os.environ["TOKENIZERS_PARALLELISM"] = "false"

# # # Load the TLQA datasets in kaggle
# # with open('mid-output-update/prompt_with_KNN/test_TLQA_with_KNN_k=3_OnlyQA.json', 'r') as file:
# #     test_tlqa_data = json.load(file)

# # Initialize the RAG retriever models
# retriever_model_name = "facebook/contriever"
# retriever_tokenizer = AutoTokenizer.from_pretrained(retriever_model_name)
# retriever_model = AutoModel.from_pretrained(retriever_model_name)

# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# retriever_model.to(device)

# # Function to get context from Wikidata based on the type
# def get_wikidata_context(wikidata_id, type_id):
#     sparql_url = "https://query.wikidata.org/sparql"
#     query = f"""
#     SELECT ?item ?itemLabel ?relatedItem ?relatedItemLabel WHERE {{
#       wd:{wikidata_id} wdt:{type_id} ?relatedItem .
#       SERVICE wikibase:label {{ bd:serviceParam wikibase:language "en". }}
#     }}
#     """
#     headers = {'Accept': 'application/json'}
#     response = requests.get(sparql_url, params={'query': query}, headers=headers)

#     if response.status_code != 200:
#         return []

#     try:
#         data = response.json()
#     except json.JSONDecodeError as e:
#         return []

#     if 'results' in data and 'bindings' in data['results'] and data['results']['bindings']:
#         related_items = []
#         for binding in data['results']['bindings']:
#             if 'relatedItemLabel' in binding:
#                 related_items.append(binding['relatedItemLabel']['value'])
#         print(related_items)
#         return related_items
#     return []

# # Function to embed text using the retriever model
# def embed_text(text, tokenizer, model):
#     inputs = tokenizer(text, return_tensors="pt", truncation=True, padding="max_length", max_length=512).to(device)
#     with torch.no_grad():
#         outputs = model(**inputs)
#     return outputs.last_hidden_state.mean(dim=1)

# # Function to retrieve context using the retriever model
# # def retrieve_context(question, contexts, top_k=2):
# #     question_embedding = embed_text(question, retriever_tokenizer, retriever_model)
# #     context_embeddings = [embed_text(context, retriever_tokenizer, retriever_model) for context in contexts]
# #     similarities = cosine_similarity(question_embedding.cpu().numpy(), torch.vstack([ce.cpu() for ce in context_embeddings]).numpy())
# #     top_k_indices = similarities[0].argsort()[-top_k:][::-1]
# #     return [contexts[i] for i in top_k_indices]

# def retrieve_context(question, contexts):
#     question_embedding = embed_text(question, retriever_tokenizer, retriever_model)
#     context_embeddings = [embed_text(context, retriever_tokenizer, retriever_model) for context in contexts]
#     similarities = cosine_similarity(question_embedding.cpu().numpy(), torch.vstack([ce.cpu() for ce in context_embeddings]).numpy())
#     top_k_indices = similarities[0].argsort()[::-1]
#     return [contexts[i] for i in top_k_indices]


# # Main processing function
# def process_data(test_data):
#     for item in test_data:
#         question = item['question']
#         wikidata_id = item['wikidata_ID']
#         type_id = item['type']

#         context = get_wikidata_context(wikidata_id, type_id)
#         if not context:
#             item['rag_contexts'] = []
#             continue

#         top_k_contexts = retrieve_context(question, context)
#         item['rag_contexts'] = top_k_contexts

#     return test_data



In [13]:
# start_time = time.time()

# # Process the data
# top_k = 3
# processed_test_data = process_data(test_tlqa_data, top_k)

# t=0
# m=0
# # Save the processed data with different values of k
# for item in processed_test_data:
#     if len(item['rag_contexts']) > 0:
#         t += 1
#     if len(item['rag_contexts']) > 1:
#         m += 1

# #     output_file_path = f'/kaggle/working/test_TLQA_with_KNN_RAG_k={k}_testk{top_k}.json'
# #     with open(output_file_path, 'w') as file:
# #         json.dump(processed_test_data, file, indent=4)

# end_time = time.time()
# print(f"Processed all items in {end_time - start_time:.2f} seconds.")
# print(f"t={t}, m={m}")

['Stevenage F.C.', 'Chelsea F.C.', 'Luton Town F.C.', 'Crewe Alexandra F.C.', 'Oldham Athletic A.F.C.', 'Port Vale F.C.', 'Southend United F.C.', 'Wycombe Wanderers F.C.']
[7 4 3]
['President of Ukraine', 'Chairman of the Verkhovna Rada', 'Prime Minister of Ukraine', "People's Deputy of Ukraine", 'First Deputy Prime Minister of Ukraine', 'Head of the Security Service of Ukraine', 'Secretary of National Security and Defense Council of Ukraine']
[1 4 6]
['Socialist Party', 'RISE (Ireland)']
[0 1]
['Amiens SC']
[0]
['Andrew Furey']
[0]
['University of Melbourne', 'University of Sydney', 'University of Toyama', 'Universiti Teknologi MARA', 'King Saud University']
[1 0 3]
['Taoiseach', 'deputy mayor', 'Teachta Dála', 'Tánaiste', 'Leader of Fine Gael', 'Minister for Defence', 'Irish Minister for Health', 'Minister for Jobs, Enterprise and Innovation', 'Minister for Social Protection', 'Minister for Transport, Tourism and Sport']
[9 5 8]
['Sergey Yaromko']
[0]
['Newport County A.F.C.', 'Cardi

In [16]:
# with open('./mid-output-update/prompt_with_KNN/test_TLQA_with_KNN_k=3_OnlyQA.json', 'r') as file:
#     test_tlqa_data = json.load(file)

# processed_test_data = process_data(test_tlqa_data)

# # Save the processed data with different values of k
# for k in [3, 5, 7, 10]:
#     for i in range(len(processed_test_data)):
#         item = processed_test_data[i]
#         item_new = test_tlqa_data[i]
#         if len(item['rag_contexts']) < k:
#             rag_text = " ".join(item['rag_contexts'])
#         else:
#             rag_text = " ".join(item['rag_contexts'][:k])
        
#         item_new['question_with_KNN_RAG'] = item_new['question_with_KNN_example'] + " " + rag_text

#     output_file_path = f'./mid-output-update/prompt_with_KNN_RAG_new/test_TLQA_with_3NN_RAG_k={k}.json'
#     with open(output_file_path, 'w') as file:
#         json.dump(processed_test_data, file, indent=4)


['Stevenage F.C.', 'Chelsea F.C.', 'Luton Town F.C.', 'Crewe Alexandra F.C.', 'Oldham Athletic A.F.C.', 'Port Vale F.C.', 'Southend United F.C.', 'Wycombe Wanderers F.C.']
['President of Ukraine', 'Chairman of the Verkhovna Rada', 'Prime Minister of Ukraine', "People's Deputy of Ukraine", 'First Deputy Prime Minister of Ukraine', 'Head of the Security Service of Ukraine', 'Secretary of National Security and Defense Council of Ukraine']
['Socialist Party', 'RISE (Ireland)']
['Amiens SC']
['Andrew Furey']
['University of Melbourne', 'University of Sydney', 'University of Toyama', 'Universiti Teknologi MARA', 'King Saud University']
['Taoiseach', 'deputy mayor', 'Teachta Dála', 'Tánaiste', 'Leader of Fine Gael', 'Minister for Defence', 'Irish Minister for Health', 'Minister for Jobs, Enterprise and Innovation', 'Minister for Social Protection', 'Minister for Transport, Tourism and Sport']
['Sergey Yaromko']
['Newport County A.F.C.', 'Cardiff City F.C.', 'Crystal Palace F.C.', 'Derby Count

In [22]:
# with open('./mid-output-update/prompt_with_KNN/test_TLQA_with_KNN_k=10_OnlyQA.json', 'r') as file:
#     test_tlqa_data_new = json.load(file)

# for k in [3, 5, 7, 10]:
#     for i in range(len(processed_test_data)):
#         item = processed_test_data[i]
#         item_new = test_tlqa_data_new[i]
#         item_new['rag_contexts'] = item['rag_contexts']
#         if len(item['rag_contexts']) < k:
#             rag_text = ", ".join(item['rag_contexts'])
#         else:
#             rag_text = ", ".join(item['rag_contexts'][:k])
        
#         item_new['question_with_KNN_RAG'] = item_new['question_with_KNN_example'] + " " + rag_text

#     output_file_path = f'./mid-output-update/prompt_with_KNN_RAG_new/test_TLQA_with_10NN_RAG_k={k}.json'
#     with open(output_file_path, 'w') as file:
#         json.dump(test_tlqa_data_new, file, indent=4)

In [ ]:
# for k in [3, 5, 7, 10]:
#     for i in range(len(processed_test_data)):
#         item = processed_test_data[i]
#         item_new = test_tlqa_data[i]
#         if len(item['rag_contexts']) < k:
#             rag_text = ", ".join(item['rag_contexts'])
#         else:
#             rag_text = ", ".join(item['rag_contexts'][:k])
        
#         item_new['question_with_KNN_RAG'] = item_new['question_with_KNN_example'] + " " + rag_text

#     output_file_path = f'./mid-output-update/prompt_with_KNN_RAG_new/test_TLQA_with_3NN_RAG_k={k}.json'
#     with open(output_file_path, 'w') as file:
#         json.dump(processed_test_data, file, indent=4)

# Inference

In [7]:
import json
import torch
from transformers import T5Tokenizer, T5ForConditionalGeneration
from torch.utils.data import DataLoader, Dataset

# class TLQADataset(Dataset):
#     def __init__(self, data, tokenizer, max_length=512):
#         self.data = data
#         self.tokenizer = tokenizer
#         self.max_length = max_length

#     def __len__(self):
#         return len(self.data)

#     def __getitem__(self, idx):
#         item = self.data[idx]
#         inputs = item['question_with_KNN_example']
#         targets = ["; ".join(item['answers'])]  # Join list of answers with a separator
#         model_inputs = self.tokenizer(inputs, max_length=self.max_length, truncation=True, padding="max_length", return_tensors="pt")
#         labels = self.tokenizer(targets, max_length=self.max_length, truncation=True, padding="max_length", return_tensors="pt", text_target=targets)
#         return {
#             'input_ids': model_inputs['input_ids'].squeeze(0),
#             'attention_mask': model_inputs['attention_mask'].squeeze(0),
#             'labels': labels['input_ids'].squeeze(0),
#             'question': inputs,
#             'answers': item['answers']  # Include the actual answers for comparison
#         }
    
class TLQADataset(Dataset):
    def __init__(self, data, tokenizer, max_length=512):
        self.data = data
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        inputs = item['question_with_KNN_RAG']
        targets = ["; ".join(item['answers'])]  # Join list of answers with a separator
        model_inputs = self.tokenizer(inputs, max_length=self.max_length, truncation=True, padding="max_length", return_tensors="pt")
        labels = self.tokenizer(text_target=targets, max_length=self.max_length, truncation=True, padding="max_length", return_tensors="pt")
        return {
            'input_ids': model_inputs['input_ids'].squeeze(0),
            'attention_mask': model_inputs['attention_mask'].squeeze(0),
            'labels': labels['input_ids'].squeeze(0),
            'question': inputs,
            'answers': item['answers']  # Include the actual answers for comparison
        }

In [8]:
# def collate_fn(batch):
#     input_ids = torch.stack([item['input_ids'] for item in batch])
#     attention_mask = torch.stack([item['attention_mask'] for item in batch])
#     labels = torch.stack([item['labels'] for item in batch])
#     questions = [item['question'] for item in batch]
#     answers = [item['answers'] for item in batch]
#     return {'input_ids': input_ids, 'attention_mask': attention_mask, 'labels': labels, 'question': questions, 'answers': answers}

def collate_fn(batch):
    input_ids = torch.stack([item['input_ids'] for item in batch])
    attention_mask = torch.stack([item['attention_mask'] for item in batch])
    labels = torch.stack([item['labels'] for item in batch])
    questions = [item['question'] for item in batch]
    answers = [item['answers'] for item in batch]
    return {'input_ids': input_ids, 'attention_mask': attention_mask, 'labels': labels, 'question': questions, 'answers': answers}


In [14]:
# def generate_answers(outputs, tokenizer):
#     decoded_outputs = [tokenizer.decode(output, skip_special_tokens=True) for output in outputs]
#     return [output.split("; ") for output in decoded_outputs]

# def generate_answers(outputs, tokenizer):
#     decoded_outputs = [tokenizer.decode(output, skip_special_tokens=True) for output in outputs]
#     # formatted_outputs = [eval(output) if output.startswith("[") else [output] for output in decoded_outputs]
#     return decoded_outputs

In [9]:
# def generate_answers(outputs, tokenizer):
#     decoded_outputs = [tokenizer.decode(output, skip_special_tokens=True) for output in outputs]
#     formatted_outputs = ["; ".join(output.split("; ")) for output in decoded_outputs]  # 确保答案用分号分隔
#     return formatted_outputs

def generate_answers(outputs, tokenizer):
    decoded_outputs = [tokenizer.decode(output, skip_special_tokens=True) for output in outputs]
    formatted_outputs = ["; ".join(output.split("; ")) for output in decoded_outputs]
    return formatted_outputs

In [10]:
# # Load the Flan-T5 model and tokenizer
# tokenizer = T5Tokenizer.from_pretrained('google/flan-t5-xl')
# model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-xl", device_map="auto", torch_dtype=torch.float16)

# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# model.to(device)

# Load the Flan-T5 model and tokenizer
tokenizer = T5Tokenizer.from_pretrained('google/flan-t5-large')
model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-large")
# model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-xl", torch_dtype=torch.float16)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

T5ForConditionalGeneration(
  (shared): Embedding(32128, 2048)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 2048)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=2048, out_features=2048, bias=False)
              (k): Linear(in_features=2048, out_features=2048, bias=False)
              (v): Linear(in_features=2048, out_features=2048, bias=False)
              (o): Linear(in_features=2048, out_features=2048, bias=False)
              (relative_attention_bias): Embedding(32, 32)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=2048, out_features=5120, bias=False)
              (wi_1): Linear(in_features=2048, out_features=5120, bias=False)
       

In [11]:
# Load test data
with open('/kaggle/input/tlqa-withknn/test_TLQA_with_10NN_RAG_k3.json', 'r') as file:
    test_data = json.load(file)

In [12]:
# Create dataset and dataloader
dataset = TLQADataset(test_data, tokenizer)
dataloader = DataLoader(dataset, batch_size=4, collate_fn=collate_fn)

model.eval()
predictions = []
actual_answers = []

# with torch.no_grad():
#     for batch in dataloader:
#         input_ids = batch['input_ids'].to(device)
#         attention_mask = batch['attention_mask'].to(device)
#         outputs = model.generate(input_ids, attention_mask=attention_mask, max_length=512, num_beams=5, early_stopping=True)
#         batch_predictions = generate_answers(outputs, tokenizer)
#         predictions.extend(batch_predictions)
#         actual_answers.extend(batch['answers'])
        
        #torch.cuda.empty_cache()
        
with torch.no_grad():
    for batch in dataloader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        outputs = model.generate(input_ids, attention_mask=attention_mask, max_length=512, num_beams=5, early_stopping=True)
        batch_predictions = generate_answers(outputs, tokenizer)
        predictions.extend(batch_predictions)
        actual_answers.extend(batch['answers'])


OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 13.06 MiB is free. Process 3814 has 14.73 GiB memory in use. Of the allocated memory 13.44 GiB is allocated by PyTorch, and 1.17 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

In [8]:
with open('10NN_RAG_predictions-FlanT5-large-k=3.json', 'w') as f:
    json.dump(predictions, f)

In [ ]:
# # Perform inference on test set
# def generate_answers(batch):
#     inputs = batch['input_ids'].to(model.device)
#     outputs = model.generate(
#         inputs,
#         max_length=64,
#         num_beams=5,
#         early_stopping=True,
#         repetition_penalty=2.5,
#         length_penalty=1.0,
#         no_repeat_ngram_size=2,
#         num_return_sequences=1  # Generate a single sequence per input
#     )
#     decoded_outputs = tokenizer.batch_decode(outputs, skip_special_tokens=True)
#     return [output.split("; ") for output in decoded_outputs]

In [ ]:
# # Trainer
# training_args = TrainingArguments(
#     output_dir="./results-FlanT5-base",
#     evaluation_strategy="epoch",
#     per_device_eval_batch_size=1
# )

# trainer = Trainer(
#     model=model,
#     args=training_args
# )

In [ ]:
# predictions = []
# for batch in trainer.get_test_dataloader(tokenized_test):
#     batch_predictions = generate_answers(batch)
#     predictions.extend(batch_predictions)